#ifndef __GUI__
#define __GUI__

#define WORKER_UPDATE 50003
#define WORKER_SUCCESS 50004
#define WORKER_FAILURE 50005

/**
@file
Subclass of GrassGen, which is generated by wxFormBuilder.
*/

#include "GrassGen.h"
#include "includes.h"
#include "Funcs.h"
#include "Ini.h"


/** Implementing GrassGen */
class GUI : public GrassGen {
private:

    struct FileTime {
        std::filesystem::path file;
        std::filesystem::file_time_type time;
    };

    static bool timeSort(FileTime i, FileTime j) { return (i.time < j.time); }

    std::optional<std::string> getRegKey(const char* pos, const char* name);

protected:
    void sendStatusUpdate(int progressPercent, const std::string &message) {
        wxCommandEvent evt(wxEVT_COMMAND_MENU_SELECTED, WORKER_UPDATE);
        evt.SetInt(progressPercent);
        evt.SetString(message);
        wxPostEvent(this, evt);
    }

    void sendSuccess() {
        wxCommandEvent evt(wxEVT_COMMAND_MENU_SELECTED, WORKER_SUCCESS);
        wxPostEvent(this, evt);
    }

    void sendFailure(const std::string &message) {
        wxCommandEvent evt(wxEVT_COMMAND_MENU_SELECTED, WORKER_FAILURE);
        evt.SetString(message);
        wxPostEvent(this, evt);
    }

    void OnThreadStatusUpdate(wxCommandEvent &event) {
        mProgBar->SetValue(event.GetInt());
        mStatus->SetStatusText(event.GetString());
    }

    void OnThreadSuccess(wxCommandEvent &event) {
        mProgBar->SetValue(100);
        mStatus->SetStatusText("Success");
        mGenerate->Enable(true);
    }

    void OnThreadFailure(wxCommandEvent &event) {
        mGenerate->Enable(true);
        mProgBar->SetValue(0);
        mStatus->SetStatusText("Failed");
        wxMessageBox(event.GetString(), wxT("Something went wrong"), wxICON_ERROR);
    }

    // Handlers for GrassGen events.
    void OnImportPress(wxCommandEvent &event);

    void OnAddPress(wxCommandEvent &event);

    void OnRemovePress(wxCommandEvent &event);

    void OnGenPress(wxCommandEvent &event);

DECLARE_EVENT_TABLE()

public:
    /** Constructor */
    GUI(wxWindow *parent);
};

#endif // __GUI__
