#ifndef __SettingsEditor__
#define __SettingsEditor__

/**
@file
Subclass of SettingsEditorFrame, which is generated by wxFormBuilder.
*/

#include "GrassGen.h"
#include <wx/msgdlg.h>


#include "SettingsEditor.h"
#include "includes.h"
#include "Funcs.h"
#include "Ini.h"


/** Implementing SettingsEditorFrame */
class SettingsEditor : public SettingsEditorFrame
{
private:
	GrassIni2* mIni;
	std::string mLastSelection;

	long mMeshListSel,mNAListSel, mLastTexSel;

	void saveCurrentSettings(const std::string& cat);

	void showError(const char* msg, const char* src);
protected:
	// Handlers for SettingsEditorFrame events.
	void OnIniLoad( wxCommandEvent& event );
	void OnIniSave( wxCommandEvent& event );
	void OnTextureChange( wxListEvent& event );
	void OnTextureAdd( wxCommandEvent& event );
	void OnTextureRemove( wxCommandEvent& event );
	void OnSclMinChanged( wxScrollEvent& event );
	void OnSclMaxChanged( wxScrollEvent& event );
	void OnPosMinChanged( wxCommandEvent& event );
	void OnPosMaxChanged( wxCommandEvent& event );
	void OnMeshInput( wxCommandEvent& event );
	void OnChanceInput( wxCommandEvent& event );
	void OnMeshAdd( wxCommandEvent& event );
	void OnMeshRemove( wxCommandEvent& event );
	void OnMeshSelect( wxListEvent& event );
	void OnGrassSelect( wxCommandEvent& event );
	void OnMeshBrowse( wxCommandEvent& event );
	void OnObjectIDInput( wxCommandEvent& event );

	void OnNotAllowAdd( wxCommandEvent& event );
	void OnNotAllowRemove( wxCommandEvent& event );
	void OnGrassInput( wxCommandEvent& event );
	void OnOffsetInput( wxCommandEvent& event );
	void OnNASelect( wxListEvent& event );

	void OnGrassListImport ( wxCommandEvent& event );
public:
	/** Constructor */
	SettingsEditor( wxWindow* parent );
};

#endif // __SettingsEditor__
