name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          # Disabled mac os as it is expensive
          #- macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install mac dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install wxwidgets boost
      - name: Build windows dependencies
        if: ${{ matrix.os == 'windows-latest' }}
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: wxwidgets boost-algorithm boost-random boost-test boost-multi-array boost-property-tree
          triplet: x64-windows-static
          token: ${{ github.token }}
          github-binarycache: true
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} ..
          cmake --build . --config Release
      - name: Make release directory, copy common artifacts
        run: |
          mkdir release
          cp README.md release/README.md.txt
          cp LICENCE.txt release/LICENCE.txt
          cp CHANGELOG.md release/CHANGELOG.md.txt

          mkdir -p release/docs/examples

          cp package/grass_cell_ref.ini release/docs/grass_cell_ref.ini
          cp package/grass_general_info.ini release/docs/grass_general_info.ini

          cp tst/snapshots/any_named_cell_exclusion/configuration.ini release/docs/examples/any_named_cell_exclusion.ini
          cp tst/snapshots/bans/configuration.ini release/docs/examples/bans.ini
          cp tst/snapshots/cell_name_exclusion/configuration.ini release/docs/examples/cell_name_exclusion.ini
          cp tst/snapshots/region_exclusion/configuration.ini release/docs/examples/region_exclusion.ini
      - name: Copy windows artifacts to the release directory
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cp build/Release/MWMeshGen.exe release/MWMeshGen.exe
      - name: Copy macos artifacts to the release directory
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cp build/MWMeshGen release/MWMeshGen
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: release/
          if-no-files-found: error