name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [
          { runner: 'windows-latest', type: 'windows', architecture: 'x64' },
        ]
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install mac dependencies
        if: ${{ matrix.os.type == 'macos' }}
        run: |
          brew install wxwidgets boost spdlog fmt
      - name: Build windows dependencies
        if: ${{ matrix.os.type == 'windows' }}
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: wxwidgets boost-algorithm boost-random boost-test boost-multi-array boost-property-tree spdlog fmt
          triplet: x64-windows-static
          token: ${{ github.token }}
          github-binarycache: true
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} ..
          cmake --build . --config Release --target MWGroundcoverGenerator
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'artifacts-${{ matrix.os.type }}-${{ matrix.os.architecture }}'
          path: build
          if-no-files-found: error